# -*- coding: utf-8 -*-
"""Avance 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i0eesm-2e81muSlSSq-mFpz6IyG4Zngk
"""

# agente carro
# velocidad
# posicion?
# estado? acelerando/desacelerando
# largo
# distancia deseada
# velocidad deseada
# diferencia distancia con proximo vehiculo
# identificador del vehiculo

# recibir variables de entorno:
# vehiculo delante
# el carro de enfrente se guia solamente por el semaforo

# funciones
# avanzar (acelerar tomando en cuenta vehiculo de enfrente y/o semaforo)


# semaforo
# zona roja: frenar
# zona amarilla: desacelerar

# Importaciones necesarias
!pip install agentpy
import agentpy as ap
import numpy as np
import random as ran

#Agente
class Car(ap.Agent):

  def setup(self):


  def update(self):

#Agente
class Spotlight(ap.Agent):

  def setup(self):


  def update(self):

#Modelo
class StreetModel(ap.Model):
  def setup(self):


  def step(self):


  def end(self):

#Parámetros
parameters = {
    
}

# Muestra de resultados
model = StreetModel(parameters)
results = model.run()
results.info